---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-goodbye
  namespace: tekton-pipelines
spec:
  params:
    - name: repository
      type: string
    - name: revision
      type: string
  tasks:
    - name: hello
      taskRef:
        name: hello
      params:
        - name: repository
          value: "$(params.repository)"
        - name: revision
          value: "$(params.revision)"
    - name: goodbye
      runAfter:
        - hello
      taskRef:
        name: goodbye