---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: checkov-scan
  namespace: tekton-pipelines
spec:
  params:
    - name: repository
      type: string
    - name: revision
      type: string
    - name: namespace
      type: string
  tasks:
    - name: scan
      taskRef:
        name: checkov-scan
      params:
        - name: repository
          value: "$(params.repository)"
        - name: revision
          value: "$(params.revision)"
        - name: namespace
          value: "$(params.namespace)"