apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: tekton-flux-eventlistener
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: flux-tekton-triggerbinding
      bindings:
        - ref: flux-tekton-triggerbinding
      template:
        ref: flux-tekton-triggertemplate