---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: flux-tekton-triggertemplate
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: staging
    - name: gitrepositoryurl
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: flux-scan-
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: hello-goodbye
        params:
          - name: repository
            value: '$(tt.params.repository)'
          - name: revision
            value: '$(tt.params.revision)'