---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
  namespace: tekton-pipelines
spec:
  params:
    - name: repository
      type: string
    - name: revision
      type: string
  steps:
    - name: echo
      image: alpine
      script: |
        #!/bin/sh
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
        kubectl version --client
        kubectl get all -A
        echo "$(params.repository)"
        echo "$(params.revision)"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: goodbye
  namespace: tekton-pipelines
spec:
  steps:
    - name: goodbye
      image: ubuntu
      script: |
        #!/bin/bash
        echo "Goodbye World!"
...
